### PR TITLE
Deprecate EventDispatcherTrait

### LINKED ISSUE #4313: Deprecate, disuse EventDispatcherTrait
### Current Behavior

Many services use `Drupal\common\EventDispatcherTrait` because we needed a backwards-compatibility layer between Drupal 8 and 9. See: https://github.com/GetDKAN/dkan/issues/3592

Currently, no one should be using Drupal 8, and we don't have Drupal 9 in our testing matrix.

Furthermore, services should be injected into other services, avoiding the `\Drupal` pattern.

So let's deprecate `EventDispatcherTrait` and remove its usage in DKAN.

### Expected Behavior

- Add a `@deprecated` annotation to `EventDispatcherTrait`.
- Inject the `event_dispatcher` service into classes that currently use the trait.
- Modify those classes to use their own dispatcher instead of the one called in the trait.

### Steps To Reproduce

See that we use EventDispatcherTrait.

Decide that it's not a good pattern.

Fix it.

### Relevant log output (optional)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by zedmonds96**
Fixes #4313

## Describe your changes

- Added a `@deprecated` annotation to `EventDispatcherTrait.php`
- All usages of the trait have been removed, replaced with direct injection of the `event_dispatcher` service.
- All classes now dispatch events through explicitly injected services instead of relying on global or trait-based dispatching.
- Since this is an injected service rather than a trait, many classes and tests needed updated with new arguments, etc. 

## QA Steps

- N/A

## Checklist before requesting review

_If any of these are left unchecked, please provide an explanation_

- [x] I have updated or added tests to cover my code
- [x] I have updated or added documentation

### CODE REVIEW

**Comment by zedmonds96** [comment]
Codeclimate has complaints about 5 arguments in constructors instead of 4. Dan F. and Paul M. were in agreement that this could be ignored for now. Also the MetastoreServices file has a few too many lines. If this is an issue, I can try to reduce it in size, but I'm not sure how that could be accomplished.

File: modules/metastore/src/MetastoreService.php [hunk 1]
```diff
@@ -78,12 +84,45 @@ public function __construct(
...
+   *   The event name.
+   * @param mixed $data
+   *   The data to dispatch.
+   * @param callable|null $validate
+   *   Optional validation callback.
+   *
+   * @return mixed
+   *   The (possibly) modified data.
+   */
+  private function dispatchEvent(string $eventName, $data, callable $validate = NULL) {
```
Comment (zedmonds96) [inline modules/metastore/src/MetastoreService.php]: This is one thing I'm not sure about. The getAll function dispatched an event with a validator function. This was the only way I could find to replicate that.

File: modules/metastore/src/MetastoreService.php [hunk 2]
```diff
@@ -179,15 +218,8 @@ public function getAll(string $schema_id, ?int $start = NULL, ?int $length = NUL
...
 
     return $this->dispatchEvent(self::EVENT_DATA_GET_ALL, $objects, function ($data) {
-      if (!is_array($data)) {
-        return FALSE;
-      }
-      if (count($data) == 0) {
-        return TRUE;
-      }
-      return reset($data) instanceof RootedJsonData;
+      return !is_array($data) ? FALSE : (count($data) === 0 || reset($data) instanceof RootedJsonData);
```
Comment (zedmonds96) [inline modules/metastore/src/MetastoreService.php]: I think this is logically equivalent, I hope functionality is retained. It was not returning the correct value in it's original state.

File: modules/metastore/src/MetastoreService.php [hunk 3]
```diff
@@ -78,12 +84,45 @@ public function __construct(
...
+   *   The data to dispatch.
+   * @param callable|null $validate
+   *   Optional validation callback.
+   *
+   * @return mixed
+   *   The (possibly) modified data.
+   */
+  private function dispatchEvent(string $eventName, $data, callable $validate = NULL) {
+    $event = new GenericEvent($data);
+    $event = $this->eventDispatcher->dispatch($event, $eventName);
```
Comment (dafeder) [inline modules/metastore/src/MetastoreService.php]:
```suggestion
    $this->eventDispatcher->dispatch($event, $eventName);
```

File: modules/common/tests/src/Unit/Events/EventTest.php [hunk 4]
```diff
@@ -11,28 +10,26 @@
...
+      ->add(Container::class, 'get', $eventDispatcher)
       ->getMock();
 
     \Drupal::setContainer($container);
 
-    $this->dispatchEvent('test_event', 'hello', function($data) {
-      return is_string($data);
-    });
+    $event = new Event('hello');
+    $eventDispatcher->dispatch($event, 'test_event');
```
Comment (dafeder) [inline modules/common/tests/src/Unit/Events/EventTest.php]: Pass validation function to Event constructor, not dispatch()

File: modules/metastore/src/MetastoreService.php (hunk 1 above)
Comment (dafeder) [reply modules/metastore/src/MetastoreService.php]: Let's try to pass the validator function to the event constructor like before, just need to use Drupal\common\Event instead of GenericEvent. Hopefully this means you can accomplish all this with just a couple lines and not need a dispatchEvent() method here.

**Review by dafeder — CHANGES_REQUESTED** [review]

File: modules/metastore/tests/src/Unit/MetastoreServiceTest.php
Comment (kaise-lafrai) [inline modules/metastore/tests/src/Unit/MetastoreServiceTest.php:1]: @dafeder How's this for a test?

Comment (dafeder) [reply modules/metastore/tests/src/Unit/MetastoreServiceTest.php:1]: LGTM!

File: modules/common/src/Storage/JobStore.php [hunk 5]
```diff
@@ -26,14 +27,21 @@ class JobStore extends AbstractDatabaseTable {
...
    * @param string $deprecatedTableName
    *   (Optional) Deprecated table name, if there is one.
    */
-  public function __construct(string $tableName, Connection $connection, string $deprecatedTableName = '') {
+  public function __construct(
+    string $tableName,
+    Connection $connection,
+    EventDispatcherInterface $eventDispatcher,
+    string $deprecatedTableName = ''
+  ) {
```
Comment (dafeder) [inline modules/common/src/Storage/JobStore.php:40]: Wondering why you added the eventDispatcher before $deprecatedTableName? Usually when you add new arguments to any function signature, especially a class constructor, you want to add them to the end to maintain compatibility with existing code or at least produce more readable errors.

**Review by dafeder — CHANGES_REQUESTED** [review]
Just one small question @zedmonds96

**Review by dafeder — CHANGES_REQUESTED** [review]
@zedmonds96 I think we decided we would just change the argument order back to the one that works. Let's get the tests passing again than figure out how to mitigate breaking changes.

**Review by dafeder — APPROVED** [review]
OK I think this is ready. This should I think be a minor/point release as it breaks the signature of a fairly important class (JobStore)

**Comment by dafeder** [comment]
> OK I think this is ready. This should I think be a minor/point release as it breaks the signature of a fairly important class (JobStore)

As @paul-m pointed out, this should be fine as JobStores are always instantiated with a Factory, so if being used correctly this shouldn't break any custom code.
