### PR TITLE
Factor out DatastoreResource class

### LINKED ISSUE #4359: Consolidate DataResource and DatastoreResource
In order to eventually sort our our circular dependency issues and get the DKAN modules organized in a more intuitive way (not to mention making the code more comprehensible) we need to collapse these two very redundant classes/objects into a single thing. The `DatastoreResource` class has very little value; it does not reference any other classes or services from the Datastore module and just adds a few more properties that are just built from the DataResource properties.

This will take a bit of trial and error to get right, but will consist of, generally

1. Figuring out how to reproduce any additional fuctionality from `DatastoreResource` in the `DataResource` class. This may involve some util-type functions that stay in Datastore and process info retrievevd from DataResource`.
2. Changing all uses of DatastoreResource throughout the Datastore module to use `DataResource` instead.  
3. Deprecating DatastoreResource but keeping for now as a shim to prevent any custom or contrib code using it from breaking.

### PR DESCRIPTION
**Pull request by dafeder**
Fixes #4359

## Describe your changes

Remove DatastoreResource class, use DataResource for everything. Note that any class or function that expected a DatastoreResource object now expects a DataResource object. So any custom code that, for instance, builds a datastore `DatabaseTable` object will need to be slightly refactored. 

Other changes to note:

* `AbstractDatabaseTable::setTable()` is now public. We should use this directly instead of calling `::count()` (as we do currently in some places) to indirectly create a database table.
* `DictionaryEnforcer` now requires the `dkan.datastore.database_table_factory` service

Please override the CC warnings when reviewing, they are due to CC getting confused by the ReturnTypeMayChange attribute. May be an issue with CC config.

## QA Steps

Nothing to QA, everything should still work as it did before from user's perspective.

## Checklist before requesting review

_If any of these are left unchecked, please provide an explanation_

- [x] I have updated or added tests to cover my code
- [x] I have updated or added documentation

### CODE REVIEW

**Comment by dafeder** [comment]
Currently debugging failing MySqlQueryDownloadControllerTest, which I think just happens to be the first test to run that tries to run a query. It fails at `AbstractDatabaseTable::setTable()`, I think something is making the perspective be `local_file` when it should be something else? It can't get a schema anyway.

**Comment by dafeder** [comment]
Some progress. Need to redo QueryDownloadControllerTest somehow... not so easy to use fake resource names because table name is no longer based on an ID in the DatastoreResource class that we can simply control via the constructor.

File: modules/json_form_widget/tests/src/Unit/StringHelperTest.php [hunk 1]
```diff
@@ -102,7 +102,6 @@ public function testHandleStringElement() {
     $data = 'mailto:john@doe.com';
 
     $result = $string_helper->handleStringElement($definition, $data);
-    print_r($result['#default_value']);
```
Comment (dafeder) [inline modules/json_form_widget/tests/src/Unit/StringHelperTest.php:105]: Not sure how this crept in here!

**Review by paul-m — CHANGES_REQUESTED** [review]
`Drupal\Tests\datastore\Unit\Storage\DatabaseTableFactoryTest` still creates a `DatastoreResource`.

**Review by paul-m — CHANGES_REQUESTED** [review]
Let's add to the docblock of `Drupal\datastore\Storage\DatabaseTableFactory::getInstance()` that the resource must be a DataResource object.

**Review by paul-m — CHANGES_REQUESTED** [review]
`Drupal\Tests\datastore\Unit\Plugin\QueueWorker\ImportJobTest` spends a lot of time making `DatastoreResource` objects.

`Drupal\Tests\datastore\Unit\Service\Info\ImportInfoTest` too.

Basically search the codebase for `DatastoreResource` and you'll see a bunch of tests.

File: modules/datastore/modules/datastore_mysql_import/src/Service/MysqlImport.php [hunk 2]
```diff
@@ -68,8 +68,12 @@ protected function runIt() {
     }
 
     // Attempt to resolve resource file name from file path.
-    if (($file_path = \Drupal::service('file_system')->realpath($this->resource->getFilePath())) === FALSE) {
-      return $this->setResultError(sprintf('Unable to resolve file name "%s" for resource with identifier "%s".', $this->resource->getFilePath(), $this->resource->getId()));
+    if (($file_path = \Drupal::service('file_system')->realpath($this->resource->getFilePath(TRUE))) === FALSE) {
+      return $this->setResultError(sprintf(
```
Comment (paul-m) [inline modules/datastore/modules/datastore_mysql_import/src/Service/MysqlImport.php:72]: Needs test coverage, since we might be inadvertently modifying the logic.

File: modules/common/tests/src/Unit/DataResourceTest.php [hunk 3]
```diff
@@ -18,21 +18,6 @@
  */
 class DataResourceTest extends TestCase {
 
-  /**
```
Comment (paul-m) [inline modules/common/tests/src/Unit/DataResourceTest.php]: We should leave this test because even though it covers deprecated code, the code is still there.

**Review by paul-m — CHANGES_REQUESTED** [review]

File: modules/common/tests/src/Unit/DataResourceTest.php (hunk 3 above)
Comment (dafeder) [reply modules/common/tests/src/Unit/DataResourceTest.php]: I was having trouble getting the test to work and thought it was maybe not worth it but I'll give it another shot

File: modules/datastore/modules/datastore_mysql_import/src/Service/MysqlImport.php (hunk 2 above)
Comment (dafeder) [reply modules/datastore/modules/datastore_mysql_import/src/Service/MysqlImport.php:72]: After some discussion, this seems outside the scope of this PR. We will do a follow-up to cover this line, and maybe make it more consistent across the two ImportJob classes.

File: modules/common/tests/src/Unit/DataResourceTest.php (hunk 3 above)
Comment (dafeder) [reply modules/common/tests/src/Unit/DataResourceTest.php]: Actually it just works as is, I'm not sure why this was removed tbh! Restored.

**Comment by dafeder** [comment]
> Let's add to the docblock of `Drupal\datastore\Storage\DatabaseTableFactory::getInstance()` that the resource must be a DataResource object.

@paul-m see 2594e68

**Review by paul-m — APPROVED** [review]

**Comment by dafeder** [comment]
Putting back to draft, needs a bit more testing from @janette

**Comment by dafeder** [comment]
Update from @janette: we're good to go

**Review by janette — APPROVED** [review]
