### PR TITLE
Fix undefined class constant when attempting drush dkan:datastore:drop

### LINKED ISSUE #3197: Error running drush dkan:datastore:drop
Attempting to run `drush dkan:datastore:drop <UUID>` caused the following error:

`[error]  Error: Undefined class constant 'DEREFERENCE_OUTPUT_REFERENCE_IDS' in Drupal\datastore\Drush->drop() (line 137)...`

### PR DESCRIPTION
**Pull request by thierrydallacroce**
Attempt to address #3197

### CODE REVIEW

File: modules/datastore/src/Drush.php [hunk 1]
```diff
@@ -45,7 +45,7 @@ public function import($uuid, $deferred = FALSE) {
 
     try {
       // Load metadata with both identifier and data for this request.
-      drupal_static('metastore_dereference_method', Dereferencer::DEREFERENCE_OUTPUT_REFERENCE_IDS);
+      drupal_static('metastore_dereference_method', ResourceMapper::DEREFERENCE_YES);
```
Comment (fmizzell) [inline modules/datastore/src/Drush.php]: @thierrydallacroce I believe we can simply remove these calls to drupal_static. Dereferencing effectively always happens.

**Review by fmizzell — CHANGES_REQUESTED** [review]

File: modules/datastore/src/Drush.php (hunk 1 above)
Comment (thierrydallacroce) [reply modules/datastore/src/Drush.php]: Done in de7f9c0.
