### PR TITLE
Post import status message

### LINKED ISSUE #4384: Post import status message
### Current Behavior

When one runs a post import twice on the same resource, the original status does not get overwritten. Figure out source of bug and fix.

### Expected Behavior

When one runs a post import twice on the same resource, the post import status must reflect on the dashboard..

### Steps To Reproduce

1. Create a dataset with a data dictionary. Keep the data dictionary mode "disabled".
2. Import the dataset and run post_import jobs.
3. Confirm that the dashboard displays "N/A Disabled" error.
4. Enable distribution reference mode for data dictionaries.
5. Re-import the dataset, and run the post-import. 
6. Confirm that dashboard still displays the "N/A Disabled" error, even though the post-import alter was applied. 

See https://jira.cms.gov/browse/WCMS-20631 for sample datasets and DD JSON.

### Relevant log output (optional)

```shell

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaise-lafrai**
Fixes [#4384 ]

### Test 2.x branch to build an existing set of post import status rows in the dkan_post_import_job_status table. 

- [ ] Checkout 2.x
- [ ] run `ddev dkan-site-install`
- [ ] run `ddev dkan-sample-content`
- [ ] run `ddev drush uli`
- [ ] navigate to Datastore Import Status dashboard `/admin/dkan/datastore/status`
- [ ] run `ddev drush dkan:datastore:import 3a187a87dc6cd47c48b6b4c4785224b7`
- [ ] run `ddev drush queue:run post_import`
- [ ] Confirm Dataset _**cedcd327-4e5d-43f9-8eb1-c11850fa7c55**_ has a Post Import message: N/A Data-Dictionary Disabled
- [ ] Navigate here /admin/dkan/data-dictionary/settings and switch Dictionary Mode to "Distribution Reference"
- [ ] Create a DD /node/add/data?schema=data-dictionary following this Schema:
```
{
  "data": {
    "title": "OBJECTID",
    "fields": [
      {
        "name": "OBJECTID",
        "title": "OBJECTID",
        "type": "integer",
        "format": "default",
        "description": "OBJECTID"
      }
    ],
    "indexes": []
  }
}
```
- [ ] Navigate to Florida Bike Lanes /node/8/edit?destination=/admin/content
- [ ] In the Distribution section enter the following:
- [ ] Data Dictionary: this should be the url to the data dictionary made above.
- [ ] Data Dictionary Type: application/vnd.tableschema+json
- [ ] Save the dataset
- [ ] run `ddev drush dkan:datastore:reimport cedcd327-4e5d-43f9-8eb1-c11850fa7c55`
- [ ] run `ddev drush queue:run post_import`
- [ ] navigate to Datastore Import Status dashboard `/admin/dkan/datastore/status`
- [ ] Confirm Dataset _**cedcd327-4e5d-43f9-8eb1-c11850fa7c55**_ STILL has a Post Import message: N/A Data-Dictionary Disabled

### Test Post-Import-Status-Message to confirm a reimport and post import update the Datastore Import Status dashboard

- [ ] Checkout Post-Import-Status-Message
- [ ] run `ddev drush updatedb`
- [ ] run `ddev drush uli`
- [ ] navigate to Datastore Import Status dashboard `/admin/dkan/datastore/status`
- [ ] run `ddev drush dkan:datastore:reimport cedcd327-4e5d-43f9-8eb1-c11850fa7c55`
- [ ] run `ddev drush queue:run post_import`
- [ ] navigate to Datastore Import Status dashboard `/admin/dkan/datastore/status`
- [ ] Confirm Dataset _**cedcd327-4e5d-43f9-8eb1-c11850fa7c55**_ has a Post Import message: **done**

## Checklist before requesting review

_If any of these are left unchecked, please provide an explanation_

- [ ] I have updated or added tests to cover my code
- [ ] I have updated or added documentation

### CODE REVIEW

File: modules/common/src/DataResource.php [hunk 1]
```diff
@@ -472,4 +472,11 @@ public function generateChecksum() {
     }
   }
 
+  /**
+   * Return current Unix timestamp.
+   */
+  public function getCurrentTime() {
```
Comment (dafeder) [inline modules/common/src/DataResource.php]: This is only used for the database operations in PostImportResult and doesn't make much sense on the DataResource class. I'd say let's make current time be an argument for PostImportResult's constructor, then there's a few ways you could mock or set it in the tests to make sure a predictable value gets passed.

File: modules/datastore/datastore.install [hunk 2]
```diff
@@ -102,3 +102,21 @@ function datastore_schema() {
...
+function datastore_update_9003(&$sandbox) {
+  $schema = \Drupal::database()->schema();
+  $table_name = 'dkan_post_import_job_status';
+
+  // Drop the current primary keys.
+  $schema->dropPrimaryKey($table_name);
+
+  $query = "
+      ALTER TABLE {$table_name}
+      ADD COLUMN row_number INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
```
Comment (dafeder) [inline modules/datastore/datastore.install]: I think the convention in Druapl tables is just to use `id` for this kind of column

File: modules/datastore/datastore.install [hunk 3]
```diff
@@ -102,3 +102,21 @@ function datastore_schema() {
...
+      ADD COLUMN timestamp INT NOT NULL DEFAULT 0
```
Comment (dafeder) [inline modules/datastore/datastore.install]: I believe the column names should also be wrapped in curly braces (`{}`)?

File: modules/datastore/tests/src/Unit/Service/PostImportResultTest.php [hunk 4]
```diff
@@ -42,33 +50,55 @@ public function testStoreJobStatus() {
...
+        'resource_version' => $dataResourceMock->getVersion(),
+        'post_import_status' => 'done',
+        'post_import_error' => 'N/A',
+        'timestamp' => 1700000000,
+      ])
+      ->willReturnSelf();
+
+    $queryMock->expects($this->any())
+      ->method('execute')
+      ->willReturn(TRUE);
```
Comment (dafeder) [inline modules/datastore/tests/src/Unit/Service/PostImportResultTest.php]: Let's discuss this - I am really having trouble figuring out what is being tested here

**Review by dafeder — CHANGES_REQUESTED** [review]

File: modules/datastore/datastore.install (hunk 3 above)
Comment (kaise-lafrai) [reply modules/datastore/datastore.install]: SQL doesn't require {} around column names. Do you have any sources you could share so I can do some more research?

File: modules/datastore/datastore.install (hunk 2 above)
Comment (kaise-lafrai) [reply modules/datastore/datastore.install]: I saw a table using row_num and went with that, but 'ID' seems like a better choice here. Thank you

File: modules/common/src/DataResource.php (hunk 1 above)
Comment (kaise-lafrai) [reply modules/common/src/DataResource.php]: I originally had this method as a public method in the PostImportResult class. I had issues getting mocking it before the factory class initializes the PostImportResult object. I can change this to use Drupal\Component\Datetime\Time class in the PostImportResult and PostImportResultFactory. I can then mock getCurrentTime method from the Time class. That should work in theory. How does that sound?

File: modules/datastore/datastore.install (hunk 3 above)
Comment (dafeder) [reply modules/datastore/datastore.install]: I'm sorry I was mistaken ehre.

**Review by dafeder — APPROVED** [review]
This looks good - considering whether it requires a new minor release as it does technically contain a breaking change. I still need to finish running through QA steps
